Importing important Libraries

In [1]:
import pandas as pd
import numpy as np
# Train Test Split
from sklearn.model_selection import train_test_split

# Scaling
from sklearn.preprocessing import StandardScaler

# Models
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.svm import SVR

# Metrics
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

Load the dataset

In [2]:
path = r"D:\Guvi\Mini-project-3(ML-regression)\Content_Monetization_Modeler\youtube_ad_revenue_dataset.csv"
df = pd.read_csv(path)
df

,video_id,date,views,likes,comments,watch_time_minutes,video_length_minutes,subscribers,category,device,country,ad_revenue_usd
0,vid_3092,2024-09-24 10:50:40.993199,9936,1221.0,320.0,26497.214184,2.862137,228086,Entertainment,TV,IN,203.178237
1,vid_3459,2024-09-22 10:50:40.993199,10017,642.0,346.0,15209.747445,23.738069,736015,Gaming,Tablet,CA,140.880508
2,vid_4784,2024-11-21 10:50:40.993199,10097,1979.0,187.0,57332.658498,26.200634,240534,Education,TV,CA,360.134008
3,vid_4078,2025-01-28 10:50:40.993199,10034,1191.0,242.0,31334.517771,11.770340,434482,Entertainment,Mobile,UK,224.638261
4,vid_3522,2025-04-28 10:50:40.993199,9889,1858.0,477.0,15665.666434,6.635854,42030,Education,Mobile,CA,165.514388
...,...,...,...,...,...,...,...,...,...,...,...,...
122395,vid_2902,2024-12-14 10:50:40.993199,9853,1673.0,147.0,42075.704885,25.490195,210818,Education,Tablet,US,280.986396
122396,vid_3890,2024-07-13 10:50:40.993199,10128,1709.0,63.0,57563.703040,16.229133,878860,Music,Desktop,UK,354.612981
122397,vid_3934,2024-06-10 10:50:40.993199,10267,700.0,NaN,27549.714659,23.822365,576756,Tech,Tablet,CA,203.643106
122398,vid_4260,2024-12-22 10:50:40.993199,10240,1616.0,106.0,56967.384382,7.753099,585138,Music,Mobile,UK,351.525811
122399,vid_1056,2024-06-25 10:50:40.993199,9931,770.0,NaN,38466.837135,27.305703,517587,Tech,TV,CA,253.842824

Data Understanding

In [3]:
df.shape

(122400, 12)

In [4]:
df.columns

Index(['video_id', 'date', 'views', 'likes', 'comments', 'watch_time_minutes',
       'video_length_minutes', 'subscribers', 'category', 'device', 'country',
       'ad_revenue_usd'],
      dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122400 entries, 0 to 122399
Data columns (total 12 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   video_id              122400 non-null  object
 1   date                  122400 non-null  object
 2   views                 122400 non-null  int64
 3   likes                 116283 non-null  float64
 4   comments              116288 non-null  float64
 5   watch_time_minutes    116295 non-null  float64
 6   video_length_minutes  122400 non-null  float64
 7   subscribers           122400 non-null  int64
 8   category              122400 non-null  object
 9   device                122400 non-null  object
 10  country               122400 non-null  object
 11  ad_revenue_usd        122400 non-null  float64
dtypes: float64(5), int64(2), object(5)
memory usage: 11.2+ MB

In [6]:
df.describe()

,views,likes,comments,watch_time_minutes,video_length_minutes,subscribers,ad_revenue_usd
count,122400.000000,116283.000000,116288.000000,116295.000000,122400.000000,122400.000000,122400.000000
mean,9999.856283,1099.633618,274.396636,37543.827721,16.014165,502191.719902,252.727210
std,99.881260,519.424089,129.741739,12987.724246,8.083790,288397.470103,61.957052
min,9521.000000,195.000000,48.000000,14659.105562,2.000142,1005.000000,126.590603
25%,9933.000000,650.000000,162.000000,26366.320569,9.004695,252507.500000,199.902018
50%,10000.000000,1103.000000,274.000000,37531.990337,16.005906,503465.500000,252.749699
75%,10067.000000,1547.000000,387.000000,48777.782090,23.021260,752192.000000,305.597518
max,10468.000000,2061.000000,515.000000,61557.670089,29.999799,999997.000000,382.768254

In [7]:
df.duplicated().sum()

np.int64(2400)

In [8]:
df = df.drop_duplicates()

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df.drop("video_id",axis=1,inplace=True)

C:\Users\evm88\AppData\Local\Temp\ipykernel_4128\935421313.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop("video_id",axis=1,inplace=True)

In [11]:
df.columns

Index(['date', 'views', 'likes', 'comments', 'watch_time_minutes',
       'video_length_minutes', 'subscribers', 'category', 'device', 'country',
       'ad_revenue_usd'],
      dtype='object')

In [12]:
df.isnull().sum()

date                       0
views                      0
likes                   6000
comments                6000
watch_time_minutes      6000
video_length_minutes       0
subscribers                0
category                   0
device                     0
country                    0
ad_revenue_usd             0
dtype: int64

Filling the null values

In [25]:
df["likes"] = df["likes"].fillna(df["likes"].mean())
df["comments"] = df["comments"].fillna(df["comments"].mean())
df["watch_time_minutes"] = df["watch_time_minutes"].fillna(df["watch_time_minutes"].mean())

In [26]:
df.isnull().sum()

views                     0
likes                     0
comments                  0
watch_time_minutes        0
video_length_minutes      0
subscribers               0
ad_revenue_usd            0
year                      0
month                     0
day                       0
day_of_week               0
hour                      0
minute                    0
category_Entertainment    0
category_Gaming           0
category_Lifestyle        0
category_Music            0
category_Tech             0
device_Mobile             0
device_TV                 0
device_Tablet             0
country_CA                0
country_DE                0
country_IN                0
country_UK                0
country_US                0
engagement_rate           0
dtype: int64

In [ ]:
df = df.copy()
df["date"] = pd.to_datetime(df["date"])

df["year"] = df["date"].dt.year
df["month"] = df["date"].dt.month
df["day"] = df["date"].dt.day
df["day_of_week"] = df["date"].dt.day_of_week

df["hour"] = df["date"].dt.hour
df["minute"] = df["date"].dt.minute
#drop the original column after the extraction
df = df.drop("date", axis=1)

In [16]:
df.columns

Index(['views', 'likes', 'comments', 'watch_time_minutes',
       'video_length_minutes', 'subscribers', 'category', 'device', 'country',
       'ad_revenue_usd', 'year', 'month', 'day', 'day_of_week', 'hour',
       'minute'],
      dtype='object')

In [17]:
df

,views,likes,comments,watch_time_minutes,video_length_minutes,subscribers,category,device,country,ad_revenue_usd,year,month,day,day_of_week,hour,minute
0,9936,1221.0,320.000000,26497.214184,2.862137,228086,Entertainment,TV,IN,203.178237,2024,9,24,1,10,50
1,10017,642.0,346.000000,15209.747445,23.738069,736015,Gaming,Tablet,CA,140.880508,2024,9,22,6,10,50
2,10097,1979.0,187.000000,57332.658498,26.200634,240534,Education,TV,CA,360.134008,2024,11,21,3,10,50
3,10034,1191.0,242.000000,31334.517771,11.770340,434482,Entertainment,Mobile,UK,224.638261,2025,1,28,1,10,50
4,9889,1858.0,477.000000,15665.666434,6.635854,42030,Education,Mobile,CA,165.514388,2025,4,28,0,10,50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122395,9853,1673.0,147.000000,42075.704885,25.490195,210818,Education,Tablet,US,280.986396,2024,12,14,5,10,50
122396,10128,1709.0,63.000000,57563.703040,16.229133,878860,Music,Desktop,UK,354.612981,2024,7,13,5,10,50
122397,10267,700.0,274.349842,27549.714659,23.822365,576756,Tech,Tablet,CA,203.643106,2024,6,10,0,10,50
122398,10240,1616.0,106.000000,56967.384382,7.753099,585138,Music,Mobile,UK,351.525811,2024,12,22,6,10,50
122399,9931,770.0,274.349842,38466.837135,27.305703,517587,Tech,TV,CA,253.842824,2024,6,25,1,10,50

Encoding the categorical column using one-hot encoding

In [18]:
df = pd.get_dummies(df,columns=["category","device","country"],dtype='int',drop_first=True)

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 120000 entries, 0 to 122399
Data columns (total 26 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   views                   120000 non-null  int64
 1   likes                   120000 non-null  float64
 2   comments                120000 non-null  float64
 3   watch_time_minutes      120000 non-null  float64
 4   video_length_minutes    120000 non-null  float64
 5   subscribers             120000 non-null  int64
 6   ad_revenue_usd          120000 non-null  float64
 7   year                    120000 non-null  int32
 8   month                   120000 non-null  int32
 9   day                     120000 non-null  int32
 10  day_of_week             120000 non-null  int32
 11  hour                    120000 non-null  int32
 12  minute                  120000 non-null  int32
 13  category_Entertainment  120000 non-null  int64
 14  category_Gaming         120000 non-null  int64
 15  category_Lifestyle      120000 non-null  int64
 16  category_Music          120000 non-null  int64
 17  category_Tech           120000 non-null  int64
 18  device_Mobile           120000 non-null  int64
 19  device_TV               120000 non-null  int64
 20  device_Tablet           120000 non-null  int64
 21  country_CA              120000 non-null  int64
 22  country_DE              120000 non-null  int64
 23  country_IN              120000 non-null  int64
 24  country_UK              120000 non-null  int64
 25  country_US              120000 non-null  int64
dtypes: float64(5), int32(6), int64(15)
memory usage: 22.0 MB

Feature engineering

In [20]:
df['engagement_rate'] = (df["likes"] + df["comments"])/df["views"]

In [21]:
df

,views,likes,comments,watch_time_minutes,video_length_minutes,subscribers,ad_revenue_usd,year,month,day,...,category_Tech,device_Mobile,device_TV,device_Tablet,country_CA,country_DE,country_IN,country_UK,country_US,engagement_rate
0,9936,1221.0,320.000000,26497.214184,2.862137,228086,203.178237,2024,9,24,...,0,0,1,0,0,0,1,0,0,0.155093
1,10017,642.0,346.000000,15209.747445,23.738069,736015,140.880508,2024,9,22,...,0,0,0,1,1,0,0,0,0,0.098632
2,10097,1979.0,187.000000,57332.658498,26.200634,240534,360.134008,2024,11,21,...,0,0,1,0,1,0,0,0,0,0.214519
3,10034,1191.0,242.000000,31334.517771,11.770340,434482,224.638261,2025,1,28,...,0,1,0,0,0,0,0,1,0,0.142814
4,9889,1858.0,477.000000,15665.666434,6.635854,42030,165.514388,2025,4,28,...,0,1,0,0,1,0,0,0,0,0.236121
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122395,9853,1673.0,147.000000,42075.704885,25.490195,210818,280.986396,2024,12,14,...,0,0,0,1,0,0,0,0,1,0.184715
122396,10128,1709.0,63.000000,57563.703040,16.229133,878860,354.612981,2024,7,13,...,0,0,0,0,0,0,0,1,0,0.174961
122397,10267,700.0,274.349842,27549.714659,23.822365,576756,203.643106,2024,6,10,...,1,0,0,1,1,0,0,0,0,0.094901
122398,10240,1616.0,106.000000,56967.384382,7.753099,585138,351.525811,2024,12,22,...,0,1,0,0,0,0,0,1,0,0.168164
122399,9931,770.0,274.349842,38466.837135,27.305703,517587,253.842824,2024,6,25,...,1,0,1,0,1,0,0,0,0,0.105161

In [22]:
#Separate features and target
X = df.drop("ad_revenue_usd", axis=1)
y = df["ad_revenue_usd"]

In [ ]:
#train-test split
X_train, X_test, y_train,y_test = train_test_split(X,y,test_size=0.2, random_state=42)

#Feature scaling
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

#Define the models
models = {
    "Linear Regression" : LinearRegression(),
    "Decision Tree" : DecisionTreeRegressor(),
    "Random Forest": RandomForestRegressor(),
    "Gradient Boosting" : GradientBoostingRegressor(),
    "SVR" : SVR()
}

#train the models and store results
results = []

for name,model in models.items():
    model.fit(X_train_scaled,y_train)
    y_pred = model.predict(X_test_scaled)

    r2 = r2_score(y_test,y_pred)
    mae = mean_absolute_error(y_test,y_pred)
    rmse = np.sqrt(mean_squared_error(y_test,y_pred))

    results.append([name, r2, mae, rmse])

#crete the result table
results_df = pd.DataFrame(
    results,
    columns=["Model", "R2 Score", "MAE", "RMSE"]
)

#sort the best models

results_df = results_df.sort_values(by="R2 Score", ascending=False)
print(results_df)

               Model  R2 Score       MAE       RMSE
0  Linear Regression  0.952574  3.118559  13.479979
3  Gradient Boosting  0.952275  3.620905  13.522416
2      Random Forest  0.949856  3.586600  13.860990
4                SVR  0.946627  5.938412  14.300227
1      Decision Tree  0.898562  5.446318  19.714371

In [24]:
import joblib

# We will save the Linear Regression model (which is models["Linear Regression"])
best_model = models["Linear Regression"]

# Save the model and the scaler
joblib.dump(best_model, 'linear_regression_model.pkl')
joblib.dump(scaler, 'scaler.pkl')

# Save the list of feature columns so our app knows the exact inputs it needs
joblib.dump(list(X.columns), 'model_columns.pkl')

print("Model and Scaler successfully saved!")

Model and Scaler successfully saved!